import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/components/context-apis/authentication/AuthProvider";
import Sidebar from "@/components/common/SideBar";
import SessionProviderWrapper from "./SessionProviderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nest Control",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gray-50`}
      >
        <Toaster position="top-center" reverseOrder={false} aria-live="assertive" />
        
        <SessionProviderWrapper>
          <AuthProvider>
            <div className="flex">
              <Sidebar />
              <div>{children}</div>
            </div>
          </AuthProvider>
        </SessionProviderWrapper>

      </body>
    </html>
  );
}
